[project]
name = "comfyui_gvf"
description = "ComfyUI custom nodes to crop an image."
version = "0.0.1"
license = { text = "GNU General Public License v3.0" }
dependencies = []

[project.urls]
Repository = ""

[tool.comfy]
PublisherId = "gvfarns"
DisplayName = "ComfyUI_gvf"
Icon = ""
